CREATE TABLE IF NOT EXISTS taskfy_ranking (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  task_group_id TEXT REFERENCES taskfy_task_group(id) ON DELETE CASCADE NOT NULL,
  due_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
