CREATE TABLE IF NOT EXISTS taskfy_task_group (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  owner_id TEXT REFERENCES taskfy_user(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);